# Generated by Django 5.0.6 on 2024-07-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cabaña', models.IntegerField()),
                ('fechaEstadia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Natur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cabaña', models.IntegerField()),
                ('fechaEstadia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rayen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cabaña', models.IntegerField()),
                ('fechaEstadia', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
