# Generated by Django 5.0.6 on 2024-07-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades', '0002_costa_natur_rayen_alter_profesor_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
